//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbDataAcces1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public int id { get; set; }
        public string lugar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> aforo { get; set; }
        public Nullable<int> hour_start { get; set; }
        public Nullable<int> hour_end { get; set; }
        public Nullable<bool> hidden { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    
        public virtual detaillsponenteconferency detaillsponenteconferency { get; set; }
        public virtual Invitation Invitation { get; set; }
    }
}
