//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbDataAcces1
{
    using System;
    using System.Collections.Generic;
    
    public partial class detaillsponenteconferency
    {
        public int id { get; set; }
        public Nullable<int> idconferency { get; set; }
        public Nullable<int> idPonente { get; set; }
        public Nullable<bool> asistencia { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Ponente Ponente { get; set; }
    }
}
