//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.detaillsponenteconferency = new HashSet<detaillsponenteconferency>();
            this.Invitation = new HashSet<Invitation>();
        }
    
        public int id { get; set; }
        public string lugar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> aforo { get; set; }
        public Nullable<int> hour_start { get; set; }
        public Nullable<int> hour_end { get; set; }
        public Nullable<bool> hidden { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaillsponenteconferency> detaillsponenteconferency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Invitation> Invitation { get; set; }
    }
}
